# Generated by Django 3.1.7 on 2021-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tarefa', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
