# Generated by Django 3.1.7 on 2021-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listadetarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
